require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6

Layout/LineLength:
  AllowHeredoc: true
  AllowURI: true
  IgnoreCopDirectives: true
  Max: 120
  Exclude:
    - "test/**/*"

Metrics/AbcSize:
  Exclude:
    - "test/**/*"

Metrics/CyclomaticComplexity:
  Max: 7

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

