version: '3.7'

services:
  lib:
    build: .
    links:
      - mysql
      - postgres
    volumes:
      - ".:/activerecord_cte"

  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
    restart: always
    environment:
      MYSQL_DATABASE: activerecord_cte_test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306

  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: activerecord_cte_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    expose:
      - 5432

